### ISSUE TITLE
Dependencies in composer.json are not correct

### ISSUE THREAD

**Issue by uwej711** [dantleech/phpcr-migrations-bundle#1]
I was able to install this bundle with Symfony 2.3, but the code requires at least Symfony 2.4 to have the commands work. On the other hand is version 1.2 of phpcr-bundle required, but this works with 1.0 as well.

Cheers
Uwe

**Comment by dantleech** [comment]
What is the issue with 2.3? Would it be easy to support? 

As for the `phpcr-bundle` it would be fine to drop the requirement level.

**Comment by uwej711** [comment]
See #2
