### ISSUE TITLE
Make the migrations container aware?

### ISSUE THREAD

**Issue by coudenysj** [dantleech/phpcr-migrations-bundle#3]
I would like to use the Doctrine DocumentManager in the migrations (I'm changing some datafixture classes into migrations), but it is not possible to acces the DocumentManager.

Is this a valid request? Or am I asking ridiculous?

**Comment by dantleech** [comment]
Doctrine ORM Migrations support this, so I guess we can also: http://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html#container-aware-migrations

**Comment by coudenysj** [comment]
Exactly. I'll have a look if I can put something together.

**Comment by dantleech** [comment]
Actually, we already do :)

https://github.com/dantleech/phpcr-migrations-bundle/blob/master/Command/MigrateCommand.php#L69

**Comment by coudenysj** [comment]
I totally missed that. Thanks.

**Comment by dantleech** [comment]
Your welcome
