### ISSUE TITLE
PHP7 incompatibility

### ISSUE THREAD

**Issue by pascalwacker** [dantleech/phpcr-migrations-bundle#4]
Hi  
I tried to run some project on a PHP7 machine, which resulted in the error `PHP Fatal error: Cannot use 'String' as class name as it is reserved in /var/www/foobar/vendor/doctrine/phpcr-odm/lib/Doctrine/ODM/PHPCR/Mapping/Annotations/String.php on line 28`.

I think the issue is described here: doctrine/phpcr-odm#678. As I see it, the issue should be eliminated by updating this bundle to ~1.3 https://github.com/doctrine/DoctrinePHPCRBundle (you require only version ~1.2 https://github.com/dantleech/phpcr-migrations-bundle/blob/master/composer.json)  
Thanks in advance for checking (and if it should be the error, fixing it :))

**Comment by dantleech** [comment]
This Bundle *does* use the annotations, but only for tests. So you should not have any issues in your application, so again I think this bundle is not the culprit here.

**Comment by dantleech** [comment]
Assuming that this bundle is not the problem, closing. Reopen if you disagree
