### ISSUE TITLE
phpcr:migrations:initialize error due to undefined function PHPCR\Migrations\MigratorException()

### ISSUE THREAD

**Issue by codeinabox** [dantleech/phpcr-migrations-bundle#6]
When I run  `./app/console phpcr:migrations:initialize` I get the following error

> PHP Fatal error:  Call to undefined function PHPCR\Migrations\MigratorException() in ~/myproject/code/vendor/phpcr/phpcr-migrations/lib/Migrator.php on line 44
> 
>   [Symfony\Component\Debug\Exception\UndefinedFunctionException]
>   Attempted to call function "MigratorException" from namespace "PHPCR\Migrations".

**Comment by dantleech** [comment]
This is an issue with the main library, we are missing the `new` keyword [here](https://github.com/phpcr/phpcr-migrations/blob/master/lib/Migrator.php#L44)

It seems that you already intiialized the versioning node, so you need not do it again. However, you can delete the versioning node with the PHPCR shell, or with `phpcr:node:remove` command (or similar):

```
$ ./app/console doctrine:phpcr:node:remove phpcr:versions
```

and run the command again.

Could you create an issue (or better a pull request) on the [phpcr/phpcr-migrations](https://github.com/phpcr/phpcr-migrations) library?

**Comment by dantleech** [comment]
Fixed in https://github.com/phpcr/phpcr-migrations/pull/6
